# Data Formatting and Neural Network Explorations Pt. 2

## Min/Max Scaler (0 to 1 range) and t = 5 Testing

In [85]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
pd.set_option('display.max_columns', None)
%matplotlib inline

In [125]:
df = pd.read_csv('df.csv',index_col=0)
df.head(10)

,match_id,time,gold,top_gold,jgl_gold,mid_gold,adc_gold,sup_gold,kill_total,assist_total,opp_kill_total,opp_assist_total,r_inhib_count,r_baron_count,r_tower_count,r_herald_count,r_drag_count,b_inhib_count,b_baron_count,b_tower_count,b_herald_count,b_dragon_count,kda,opp_kda,result
0,001a1f289e3bab22_b,0.0,2415.0,475.0,475.0,475.0,475.0,515.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0
1,001a1f289e3bab22_b,1.0,2430.0,475.0,475.0,475.0,475.0,530.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0
2,001a1f289e3bab22_b,2.0,2751.0,532.0,552.0,532.0,532.0,603.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0
3,001a1f289e3bab22_b,3.0,3929.0,849.0,817.0,791.0,686.0,786.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0
4,001a1f289e3bab22_b,4.0,5219.0,1099.0,1099.0,1107.0,976.0,938.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0
5,001a1f289e3bab22_b,5.0,6418.0,1466.0,1278.0,1352.0,1196.0,1126.0,2.0,1.0,1.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.00,1.5,0.0
6,001a1f289e3bab22_b,6.0,8156.0,1667.0,1708.0,1574.0,1687.0,1520.0,2.0,1.0,3.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.00,3.5,0.0
7,001a1f289e3bab22_b,7.0,9520.0,1970.0,2097.0,1708.0,1995.0,1750.0,2.0,1.0,3.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.00,3.5,0.0
8,001a1f289e3bab22_b,8.0,10681.0,2147.0,2414.0,1988.0,2244.0,1888.0,2.0,1.0,4.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.75,4.5,0.0
9,001a1f289e3bab22_b,9.0,12036.0,2605.0,2533.0,2321.0,2535.0,2042.0,2.0,1.0,4.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.75,4.5,0.0

## Min Max Scaler

In [87]:
from sklearn.preprocessing import MinMaxScaler

data = df.iloc[:,2:-1]
scaler = MinMaxScaler(copy=True,feature_range=(0,1))
scaler.fit(data)

MinMaxScaler(copy=True, feature_range=(0, 1))

## Standard Scaler

In [126]:
from sklearn.preprocessing import StandardScaler

data = df.iloc[:,2:-1]
scaler = StandardScaler()
scaler.fit(data)

StandardScaler(copy=True, with_mean=True, with_std=True)

## Data Formatting

In [127]:
# want to keep group/result columns and add them back after scaling
cols = list(df.columns.values)
hold_out_cols = ['match_id', 'time', 'result']
ho_df = df[hold_out_cols].copy()

In [128]:
cols_scale = ['gold', 'top_gold', 'jgl_gold', 'mid_gold', 'adc_gold', 'sup_gold', 'kill_total',
 'assist_total', 'opp_kill_total', 'opp_assist_total', 'r_inhib_count', 'r_baron_count', 'r_tower_count',
 'r_herald_count', 'r_drag_count', 'b_inhib_count', 'b_baron_count', 'b_tower_count', 'b_herald_count',
 'b_dragon_count', 'kda', 'opp_kda']

In [129]:
# scale data
data = scaler.transform(data)

In [130]:
sdf = pd.DataFrame(data)
sdf.columns = cols_scale

In [131]:
sdf.head(15)

,gold,top_gold,jgl_gold,mid_gold,adc_gold,sup_gold,kill_total,assist_total,opp_kill_total,opp_assist_total,r_inhib_count,r_baron_count,r_tower_count,r_herald_count,r_drag_count,b_inhib_count,b_baron_count,b_tower_count,b_herald_count,b_dragon_count,kda,opp_kda
0,-1.342942,-1.326213,-1.387083,-1.341606,-1.320149,-1.269691,-0.899995,-0.796908,-0.899995,-0.796908,-1.742076,-2.271392,-1.401829,-2.768166,-1.835765,-1.735504,-2.43541,-1.461121,-2.877854,-1.885778,-0.712698,-0.712698
1,-1.342244,-1.326213,-1.387083,-1.341606,-1.320149,-1.264782,-0.899995,-0.796908,-0.899995,-0.796908,-1.742076,-2.271392,-1.401829,-2.768166,-1.835765,-1.735504,-2.43541,-1.461121,-2.877854,-1.885778,-0.712698,-0.712698
2,-1.327294,-1.313755,-1.368286,-1.330031,-1.308748,-1.240890,-0.899995,-0.796908,-0.899995,-0.796908,-1.742076,-2.271392,-1.401829,-2.768166,-1.835765,-1.735504,-2.43541,-1.461121,-2.877854,-1.885778,-0.712698,-0.712698
3,-1.272434,-1.244472,-1.303596,-1.277439,-1.277944,-1.180998,-0.899995,-0.796908,-0.899995,-0.796908,-1.742076,-2.271392,-1.401829,-2.768166,-1.835765,-1.735504,-2.43541,-1.461121,-2.877854,-1.885778,-0.712698,-0.712698
4,-1.212358,-1.189832,-1.234757,-1.213273,-1.219937,-1.131251,-0.899995,-0.796908,-0.899995,-0.796908,-1.742076,-2.271392,-1.401829,-2.768166,-1.835765,-1.735504,-2.43541,-1.461121,-2.877854,-1.885778,-0.712698,-0.712698
5,-1.156519,-1.109620,-1.191061,-1.163523,-1.175932,-1.069723,-0.499902,-0.714834,-0.699948,-0.632761,-1.742076,-2.271392,-1.401829,-2.768166,-1.835765,-1.735504,-2.43541,-1.461121,-2.877854,-1.885778,-0.090375,-0.401537
6,-1.075579,-1.065690,-1.086093,-1.118444,-1.077720,-0.940775,-0.499902,-0.714834,-0.299856,-0.468614,-1.742076,-2.271392,-1.401829,-2.768166,-1.835765,-1.735504,-2.43541,-1.461121,-2.877854,-1.885778,-0.505257,0.013345
7,-1.012057,-0.999466,-0.991133,-1.091234,-1.016113,-0.865500,-0.499902,-0.714834,-0.299856,-0.468614,-1.742076,-2.271392,-1.401829,-2.768166,-1.835765,-1.735504,-2.43541,-1.461121,-2.877854,-1.003943,-0.505257,0.013345
8,-0.957988,-0.960781,-0.913750,-1.034378,-0.966307,-0.820335,-0.499902,-0.714834,-0.099810,-0.386541,-1.742076,-2.271392,-1.401829,-2.768166,-1.835765,-1.735504,-2.43541,-1.461121,-2.877854,-1.003943,-0.557118,0.220787
9,-0.894885,-0.860681,-0.884700,-0.966759,-0.908100,-0.769934,-0.499902,-0.714834,-0.099810,-0.386541,-1.742076,-2.271392,-1.401829,-2.768166,-1.835765,-1.735504,-2.43541,-1.461121,-2.877854,-1.003943,-0.557118,0.220787
10,-0.818416,-0.782873,-0.785835,-0.897719,-0.833891,-0.714297,-0.299856,-0.550687,-0.099810,-0.386541,-1.742076,-2.271392,-1.401829,-2.768166,-1.835765,-1.735504,-2.43541,-1.461121,-2.877854,-1.003943,-0.401537,-0.090375
11,-0.729372,-0.713808,-0.688434,-0.832537,-0.715077,-0.622004,-0.299856,-0.550687,-0.099810,-0.386541,-1.742076,-2.271392,-1.401829,-2.768166,-1.835765,-1.735504,-2.43541,-1.461121,-2.877854,-1.003943,-0.401537,-0.090375
12,-0.673860,-0.633815,-0.635706,-0.777915,-0.683874,-0.561457,-0.099810,-0.304467,0.500329,0.023826,-1.742076,-2.271392,-1.401829,-2.768166,-1.835765,-1.735504,-2.43541,-1.461121,-2.877854,-1.003943,-0.416354,0.168926
13,-0.597717,-0.568903,-0.591278,-0.672121,-0.606464,-0.480292,-0.099810,-0.304467,0.500329,0.023826,-1.742076,-2.271392,-1.401829,-2.768166,-0.978100,-1.735504,-2.43541,-1.461121,-2.877854,-1.003943,-0.416354,0.168926
14,-0.521573,-0.484321,-0.489239,-0.605111,-0.536056,-0.431854,-0.099810,-0.304467,0.500329,0.023826,-1.742076,-2.271392,-1.401829,-2.768166,-0.978100,-1.735504,-2.43541,-1.461121,-2.877854,-1.003943,-0.416354,0.168926

In [132]:
sdf = pd.merge(sdf, ho_df, left_index=True, right_index=True)
sdf.head()

,gold,top_gold,jgl_gold,mid_gold,adc_gold,sup_gold,kill_total,assist_total,opp_kill_total,opp_assist_total,r_inhib_count,r_baron_count,r_tower_count,r_herald_count,r_drag_count,b_inhib_count,b_baron_count,b_tower_count,b_herald_count,b_dragon_count,kda,opp_kda,match_id,time,result
0,-1.342942,-1.326213,-1.387083,-1.341606,-1.320149,-1.269691,-0.899995,-0.796908,-0.899995,-0.796908,-1.742076,-2.271392,-1.401829,-2.768166,-1.835765,-1.735504,-2.43541,-1.461121,-2.877854,-1.885778,-0.712698,-0.712698,001a1f289e3bab22_b,0.0,0.0
1,-1.342244,-1.326213,-1.387083,-1.341606,-1.320149,-1.264782,-0.899995,-0.796908,-0.899995,-0.796908,-1.742076,-2.271392,-1.401829,-2.768166,-1.835765,-1.735504,-2.43541,-1.461121,-2.877854,-1.885778,-0.712698,-0.712698,001a1f289e3bab22_b,1.0,0.0
2,-1.327294,-1.313755,-1.368286,-1.330031,-1.308748,-1.240890,-0.899995,-0.796908,-0.899995,-0.796908,-1.742076,-2.271392,-1.401829,-2.768166,-1.835765,-1.735504,-2.43541,-1.461121,-2.877854,-1.885778,-0.712698,-0.712698,001a1f289e3bab22_b,2.0,0.0
3,-1.272434,-1.244472,-1.303596,-1.277439,-1.277944,-1.180998,-0.899995,-0.796908,-0.899995,-0.796908,-1.742076,-2.271392,-1.401829,-2.768166,-1.835765,-1.735504,-2.43541,-1.461121,-2.877854,-1.885778,-0.712698,-0.712698,001a1f289e3bab22_b,3.0,0.0
4,-1.212358,-1.189832,-1.234757,-1.213273,-1.219937,-1.131251,-0.899995,-0.796908,-0.899995,-0.796908,-1.742076,-2.271392,-1.401829,-2.768166,-1.835765,-1.735504,-2.43541,-1.461121,-2.877854,-1.885778,-0.712698,-0.712698,001a1f289e3bab22_b,4.0,0.0

In [133]:
fcols = [ 'match_id', 'time','gold', 'top_gold', 'jgl_gold', 'mid_gold', 'adc_gold', 'sup_gold', 'kill_total',
 'assist_total', 'opp_kill_total', 'opp_assist_total', 'r_inhib_count', 'r_baron_count', 'r_tower_count',
 'r_herald_count', 'r_drag_count', 'b_inhib_count', 'b_baron_count', 'b_tower_count', 'b_herald_count',
 'b_dragon_count', 'kda', 'opp_kda', 'result']

In [134]:
sdf1 = sdf[fcols]
sdf1.head()

,match_id,time,gold,top_gold,jgl_gold,mid_gold,adc_gold,sup_gold,kill_total,assist_total,opp_kill_total,opp_assist_total,r_inhib_count,r_baron_count,r_tower_count,r_herald_count,r_drag_count,b_inhib_count,b_baron_count,b_tower_count,b_herald_count,b_dragon_count,kda,opp_kda,result
0,001a1f289e3bab22_b,0.0,-1.342942,-1.326213,-1.387083,-1.341606,-1.320149,-1.269691,-0.899995,-0.796908,-0.899995,-0.796908,-1.742076,-2.271392,-1.401829,-2.768166,-1.835765,-1.735504,-2.43541,-1.461121,-2.877854,-1.885778,-0.712698,-0.712698,0.0
1,001a1f289e3bab22_b,1.0,-1.342244,-1.326213,-1.387083,-1.341606,-1.320149,-1.264782,-0.899995,-0.796908,-0.899995,-0.796908,-1.742076,-2.271392,-1.401829,-2.768166,-1.835765,-1.735504,-2.43541,-1.461121,-2.877854,-1.885778,-0.712698,-0.712698,0.0
2,001a1f289e3bab22_b,2.0,-1.327294,-1.313755,-1.368286,-1.330031,-1.308748,-1.240890,-0.899995,-0.796908,-0.899995,-0.796908,-1.742076,-2.271392,-1.401829,-2.768166,-1.835765,-1.735504,-2.43541,-1.461121,-2.877854,-1.885778,-0.712698,-0.712698,0.0
3,001a1f289e3bab22_b,3.0,-1.272434,-1.244472,-1.303596,-1.277439,-1.277944,-1.180998,-0.899995,-0.796908,-0.899995,-0.796908,-1.742076,-2.271392,-1.401829,-2.768166,-1.835765,-1.735504,-2.43541,-1.461121,-2.877854,-1.885778,-0.712698,-0.712698,0.0
4,001a1f289e3bab22_b,4.0,-1.212358,-1.189832,-1.234757,-1.213273,-1.219937,-1.131251,-0.899995,-0.796908,-0.899995,-0.796908,-1.742076,-2.271392,-1.401829,-2.768166,-1.835765,-1.735504,-2.43541,-1.461121,-2.877854,-1.885778,-0.712698,-0.712698,0.0

In [135]:
len(sdf1)

286844

In [136]:
# create X and y dataframes for training/testing
X = sdf1.loc[:,sdf1.columns != 'result'].values
y = sdf1.loc[:,sdf1.columns == 'result'].values
groups = sdf1['match_id']

In [137]:
from sklearn.model_selection import GroupKFold
# 80/20 split for train/test groups
gkf = GroupKFold(n_splits=5)

for train_index, test_index in gkf.split(X, y,groups):
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]

### Prepare Train Data

In [138]:
# reshape data to work with previously written parse_game function
xtrain = pd.DataFrame(X_train)
ytrain = pd.DataFrame(y_train)

In [139]:
print(len(ytrain))
print(len(xtrain))

229486
229486

In [140]:
train_df = pd.merge(xtrain, ytrain, left_index=True, right_index=True)

In [141]:
train_df.rename(columns={'0_y':'result','0_x':'match_id'},inplace=True)

In [142]:
train_df.sort_values(['match_id',1],inplace=True)
train_df.head()

,match_id,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,result
0,001a1f289e3bab22_b,0,-1.34294,-1.32621,-1.38708,-1.34161,-1.32015,-1.26969,-0.899995,-0.796908,-0.899995,-0.796908,-1.74208,-2.27139,-1.40183,-2.76817,-1.83577,-1.7355,-2.43541,-1.46112,-2.87785,-1.88578,-0.712698,-0.712698,0.0
1,001a1f289e3bab22_b,1,-1.34224,-1.32621,-1.38708,-1.34161,-1.32015,-1.26478,-0.899995,-0.796908,-0.899995,-0.796908,-1.74208,-2.27139,-1.40183,-2.76817,-1.83577,-1.7355,-2.43541,-1.46112,-2.87785,-1.88578,-0.712698,-0.712698,0.0
2,001a1f289e3bab22_b,2,-1.32729,-1.31376,-1.36829,-1.33003,-1.30875,-1.24089,-0.899995,-0.796908,-0.899995,-0.796908,-1.74208,-2.27139,-1.40183,-2.76817,-1.83577,-1.7355,-2.43541,-1.46112,-2.87785,-1.88578,-0.712698,-0.712698,0.0
3,001a1f289e3bab22_b,3,-1.27243,-1.24447,-1.3036,-1.27744,-1.27794,-1.181,-0.899995,-0.796908,-0.899995,-0.796908,-1.74208,-2.27139,-1.40183,-2.76817,-1.83577,-1.7355,-2.43541,-1.46112,-2.87785,-1.88578,-0.712698,-0.712698,0.0
4,001a1f289e3bab22_b,4,-1.21236,-1.18983,-1.23476,-1.21327,-1.21994,-1.13125,-0.899995,-0.796908,-0.899995,-0.796908,-1.74208,-2.27139,-1.40183,-2.76817,-1.83577,-1.7355,-2.43541,-1.46112,-2.87785,-1.88578,-0.712698,-0.712698,0.0

### Prepare Test Data

In [143]:
xtest = pd.DataFrame(X_test)
ytest = pd.DataFrame(y_test)
print(len(xtest))
print(len(ytest))

57358
57358

In [144]:
test_df = pd.merge(xtest, ytest, left_index=True, right_index=True)

In [145]:
test_df.rename(columns={'0_y':'result','0_x':'match_id'},inplace=True)
test_df.head()

,match_id,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,result
0,001a1f289e3bab22_r,0,-1.34294,-1.32621,-1.38708,-1.34161,-1.32015,-1.26969,-0.899995,-0.796908,-0.899995,-0.796908,-0.865652,-2.27139,0.90352,-2.76817,1.59489,-1.7355,-2.43541,-0.500126,-2.87785,-1.00394,-0.712698,-0.712698,1.0
1,001a1f289e3bab22_r,1,-1.34294,-1.32621,-1.38708,-1.34161,-1.32015,-1.26969,-0.899995,-0.796908,-0.899995,-0.796908,-0.865652,-2.27139,0.90352,-2.76817,1.59489,-1.7355,-2.43541,-0.500126,-2.87785,-1.00394,-0.712698,-0.712698,1.0
2,001a1f289e3bab22_r,2,-1.32944,-1.31376,-1.37317,-1.33003,-1.30875,-1.2494,-0.899995,-0.796908,-0.899995,-0.796908,-0.865652,-2.27139,0.90352,-2.76817,1.59489,-1.7355,-2.43541,-0.500126,-2.87785,-1.00394,-0.712698,-0.712698,1.0
3,001a1f289e3bab22_r,3,-1.26624,-1.2648,-1.28114,-1.27033,-1.24794,-1.19769,-0.899995,-0.796908,-0.899995,-0.796908,-0.865652,-2.27139,0.90352,-2.76817,1.59489,-1.7355,-2.43541,-0.500126,-2.87785,-1.00394,-0.712698,-0.712698,1.0
4,001a1f289e3bab22_r,4,-1.20956,-1.20032,-1.22402,-1.22586,-1.18893,-1.14074,-0.899995,-0.796908,-0.899995,-0.796908,-0.865652,-2.27139,0.90352,-2.76817,1.59489,-1.7355,-2.43541,-0.500126,-2.87785,-1.00394,-0.712698,-0.712698,1.0

## Parse Game Data to Reformat for Neural Network

In [146]:
def parse_game(grp):
    """Input is a single groupby object
    Output is a list of 3d arrays, each element contains 10 rows (which are equivalent to minutes 
       for this dataset). The function tracks the length of each group and stops at length minus 1. 
       After a group is finished the function performs the same process on the next group.
    """  
    t = 10
    start = 0
   
    length = len(grp)

    while t < length:
        
        # take a 10 row chunk and convert it to array
        
        data = grp.iloc[:,2:-1][start:t].values
   
        df_list.append(data)
        result_list.append(grp.iloc[:,-1:][start:t].values[0])
        
        # stop when t reaches length - 1
        start += 1
        t += 1
    
    return df_list

In [147]:
df_list = []
result_list = []

gb = train_df.groupby('match_id')

gb.apply(lambda group: parse_game(group));

In [148]:
print(len(df_list))
print(len(result_list))

169444
169444

In [149]:
num_features = 22
time_steps = 10

In [150]:
# reshape y to 1d numpy array
length_r = len(result_list)
y_train = np.array(result_list)
y_train = y_train.ravel()

In [151]:
# reshape x to 3d numpy array
length = len(df_list)
X_train = np.array(df_list)
X_train = X_train.reshape((length, time_steps, num_features))

In [152]:
def parse_game_test(grp):
    """Inputs are 1. a groupby group object
    Output is a list of 3d arrays, each element contains 10 rows (which are equivalent to minutes 
       for this dataset). The function tracks the length of each group and stops at length minus 1. 
       After a group is finished the function performs the same process on the next group.
    """  
    t = 10
    start = 0
   
    length = len(grp)

    while t < length:
        
        # take a 10 row chunk and convert it to array
        
        data = grp.iloc[:,2:-1][start:t].values
   
        df_list_test.append(data)
        result_list_test.append(grp.iloc[:,-1:][start:t].values[0])
        
        # stop when t reaches length - 1
        start += 1
        t += 1
    
    return df_list

In [153]:
df_list_test = []
result_list_test = []

gb = test_df.groupby('match_id')

gb.apply(lambda group: parse_game_test(group));

In [154]:
print(len(df_list_test))
print(len(result_list_test))

42376
42376

In [155]:
length_r = len(result_list_test)
y_test = np.array(result_list_test)
y_test = y_test.ravel()

In [156]:
length = len(df_list_test)
X_test = np.array(df_list_test)
X_test = X_test.reshape((length, time_steps, num_features))

In [157]:
print(len(X_test))
print(len(y_test))

42376
42376

## Test on current 'best' LSTM network, t=10

In [120]:
from keras.models import Sequential
from keras.layers import Dense, Dropout
from keras.layers import Embedding
from keras.layers import LSTM
from sklearn.model_selection import GridSearchCV
from keras.wrappers.scikit_learn import KerasClassifier
from keras.constraints import maxnorm

In [36]:
print(X_train[:-1].shape)
print(y_train[:-1].shape)
print(X_test.shape)
print(y_test.shape)

(169443, 10, 22)
(169443,)
(42376, 10, 22)
(42376,)

In [38]:
model = Sequential()
model.add(Dense(50,batch_input_shape=(4705, X_train[:-64].shape[1],X_train[:-64].shape[2])))
model.add(LSTM(40, stateful=True))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',
         optimizer='rmsprop',
         metrics=['accuracy'])
for i in range(10):
    model.fit(X_train[:-64], y_train[:-64], batch_size=4705,shuffle=False, epochs=1,verbose=1)
    model.reset_states()

Epoch 1/1
169380/169380 [==============================] - 13s - loss: 0.6887 - acc: 0.5377
Epoch 1/1
169380/169380 [==============================] - 11s - loss: 0.6784 - acc: 0.5593
Epoch 1/1
169380/169380 [==============================] - 11s - loss: 0.6719 - acc: 0.5691
Epoch 1/1
169380/169380 [==============================] - 11s - loss: 0.6672 - acc: 0.5757
Epoch 1/1
169380/169380 [==============================] - 11s - loss: 0.6624 - acc: 0.5821
Epoch 1/1
169380/169380 [==============================] - 11s - loss: 0.6555 - acc: 0.5919
Epoch 1/1
169380/169380 [==============================] - 11s - loss: 0.6545 - acc: 0.5931
Epoch 1/1
169380/169380 [==============================] - 11s - loss: 0.6498 - acc: 0.6019
Epoch 1/1
169380/169380 [==============================] - 11s - loss: 0.6442 - acc: 0.6096
Epoch 1/1
169380/169380 [==============================] - 11s - loss: 0.6388 - acc: 0.6157

In [41]:
score = model.evaluate(X_test[:-31], y_test[:-31], verbose=0,batch_size=4705)
score

[0.65229573514726424, 0.60054316123326623]

## Test on current 'best' LSTM network, t=5

In [72]:
print(X_train[:-4].shape)
print(y_train[:-4].shape)
print(X_test.shape)
print(y_test.shape)

(199480, 5, 22)
(199480,)
(49886, 5, 22)
(49886,)

In [73]:
model = Sequential()
model.add(Dense(50,batch_input_shape=(4987, X_train[:-4].shape[1],X_train[:-4].shape[2])))
model.add(LSTM(40, stateful=True))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',
         optimizer='rmsprop',
         metrics=['accuracy'])
for i in range(10):
    model.fit(X_train[:-4], y_train[:-4], batch_size=4987,shuffle=False, epochs=1,verbose=1)
    model.reset_states()

Epoch 1/1
199480/199480 [==============================] - 8s - loss: 0.6895 - acc: 0.5316
Epoch 1/1
199480/199480 [==============================] - 7s - loss: 0.6842 - acc: 0.5502
Epoch 1/1
199480/199480 [==============================] - 7s - loss: 0.6800 - acc: 0.5587
Epoch 1/1
199480/199480 [==============================] - 7s - loss: 0.6771 - acc: 0.5635
Epoch 1/1
199480/199480 [==============================] - 7s - loss: 0.6750 - acc: 0.5653
Epoch 1/1
199480/199480 [==============================] - 7s - loss: 0.6731 - acc: 0.5678
Epoch 1/1
199480/199480 [==============================] - 7s - loss: 0.6706 - acc: 0.5711
Epoch 1/1
199480/199480 [==============================] - 7s - loss: 0.6678 - acc: 0.5764
Epoch 1/1
199480/199480 [==============================] - 7s - loss: 0.6650 - acc: 0.5814
Epoch 1/1
199480/199480 [==============================] - 7s - loss: 0.6623 - acc: 0.5859

In [ ]:
score = model.evaluate(X_test[:-31], y_test[:-31], verbose=0,batch_size=4705)
score

## Combine all testing into 1 final model

### Final Parameters

- Dense->Dropout->LSTM->Out
- Dropout rate: 0.2 (gridsearch on dropout actually showed no dropout was best, I'll use the 2nd best result to combat overfitting)
- Weight Constraint: 1
- Neurons in 1st layer: 50
- Neurons in LSTM layer: 45
- Optimizer: rmsprop
- t=10

### Min/Max Scaler

In [124]:
model = Sequential()
model.add(Dense(50,batch_input_shape=(4705, X_train[:-64].shape[1],X_train[:-64].shape[2]),
               kernel_constraint=maxnorm(1)))
model.add(Dropout(0.2))
model.add(LSTM(45, stateful=True))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',
         optimizer='rmsprop',
         metrics=['accuracy'])

for i in range(10):
    model.fit(X_train[:-64], y_train[:-64], batch_size=4705,shuffle=False, epochs=1,verbose=1)
    model.reset_states()

Epoch 1/1
169380/169380 [==============================] - 16s - loss: 0.6895 - acc: 0.5373
Epoch 1/1
169380/169380 [==============================] - 14s - loss: 0.6805 - acc: 0.5553
Epoch 1/1
169380/169380 [==============================] - 14s - loss: 0.6741 - acc: 0.5678
Epoch 1/1
169380/169380 [==============================] - 14s - loss: 0.6706 - acc: 0.5727
Epoch 1/1
169380/169380 [==============================] - 14s - loss: 0.6667 - acc: 0.5766
Epoch 1/1
169380/169380 [==============================] - 15s - loss: 0.6628 - acc: 0.5817
Epoch 1/1
169380/169380 [==============================] - 14s - loss: 0.6587 - acc: 0.5868
Epoch 1/1
169380/169380 [==============================] - 14s - loss: 0.6525 - acc: 0.5958
Epoch 1/1
169380/169380 [==============================] - 14s - loss: 0.6475 - acc: 0.6036
Epoch 1/1
169380/169380 [==============================] - 15s - loss: 0.6436 - acc: 0.6079

In [158]:
score = model.evaluate(X_test[:-31], y_test[:-31], verbose=0,batch_size=4705)
score

[0.6911163330078125, 0.56058566437827217]

### StandardScaler

In [159]:
model = Sequential()
model.add(Dense(50,batch_input_shape=(4705, X_train[:-64].shape[1],X_train[:-64].shape[2]),
               kernel_constraint=maxnorm(1)))
model.add(Dropout(0.2))
model.add(LSTM(45, stateful=True))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',
         optimizer='rmsprop',
         metrics=['accuracy'])

for i in range(10):
    model.fit(X_train[:-64], y_train[:-64], batch_size=4705,shuffle=False, epochs=1,verbose=1)
    model.reset_states()

Epoch 1/1
169380/169380 [==============================] - 17s - loss: 0.6651 - acc: 0.5898
Epoch 1/1
169380/169380 [==============================] - 16s - loss: 0.6401 - acc: 0.6222
Epoch 1/1
169380/169380 [==============================] - 16s - loss: 0.6203 - acc: 0.6344
Epoch 1/1
169380/169380 [==============================] - 16s - loss: 0.6097 - acc: 0.6413
Epoch 1/1
169380/169380 [==============================] - 16s - loss: 0.6019 - acc: 0.6486
Epoch 1/1
169380/169380 [==============================] - 16s - loss: 0.5938 - acc: 0.6543
Epoch 1/1
169380/169380 [==============================] - 15s - loss: 0.5876 - acc: 0.6593
Epoch 1/1
169380/169380 [==============================] - 15s - loss: 0.5821 - acc: 0.6641
Epoch 1/1
169380/169380 [==============================] - 15s - loss: 0.5770 - acc: 0.6686
Epoch 1/1
169380/169380 [==============================] - 15s - loss: 0.5727 - acc: 0.6712

In [160]:
score = model.evaluate(X_test[:-31], y_test[:-31], verbose=0,batch_size=4705)
score

[0.61966190073225236, 0.62798441780938041]

### StandardScaler with no Dropout

In [161]:
model = Sequential()
model.add(Dense(50,batch_input_shape=(4705, X_train[:-64].shape[1],X_train[:-64].shape[2])))
#model.add(Dropout(0.2))
model.add(LSTM(45, stateful=True))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',
         optimizer='rmsprop',
         metrics=['accuracy'])

for i in range(10):
    model.fit(X_train[:-64], y_train[:-64], batch_size=4705,shuffle=False, epochs=1,verbose=1)
    model.reset_states()

Epoch 1/1
169380/169380 [==============================] - 15s - loss: 0.6714 - acc: 0.5776
Epoch 1/1
169380/169380 [==============================] - 14s - loss: 0.6409 - acc: 0.6176
Epoch 1/1
169380/169380 [==============================] - 15s - loss: 0.6213 - acc: 0.6320
Epoch 1/1
169380/169380 [==============================] - 15s - loss: 0.6086 - acc: 0.6431
Epoch 1/1
169380/169380 [==============================] - 15s - loss: 0.5985 - acc: 0.6513
Epoch 1/1
169380/169380 [==============================] - 15s - loss: 0.5902 - acc: 0.6577
Epoch 1/1
169380/169380 [==============================] - 15s - loss: 0.5831 - acc: 0.6633
Epoch 1/1
169380/169380 [==============================] - 15s - loss: 0.5766 - acc: 0.6675
Epoch 1/1
169380/169380 [==============================] - 15s - loss: 0.5706 - acc: 0.6721
Epoch 1/1
169380/169380 [==============================] - 15s - loss: 0.5649 - acc: 0.6765

In [162]:
score = model.evaluate(X_test[:-31], y_test[:-31], verbose=0,batch_size=4705)
score

[0.61506725682152641, 0.62751210398144197]

### Epoch=25

In [177]:
model = Sequential()
model.add(Dense(50,batch_input_shape=(4705, X_train[:-64].shape[1],X_train[:-64].shape[2]),
               kernel_constraint=maxnorm(1)))
model.add(Dropout(0.2))
model.add(LSTM(45, stateful=True))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',
         optimizer='rmsprop',
         metrics=['accuracy'])

for i in range(25):
    model.fit(X_train[:-64], y_train[:-64], batch_size=4705,shuffle=False, epochs=1,verbose=0)
    model.reset_states()

In [178]:
score = model.evaluate(X_test[:-31], y_test[:-31], verbose=0,batch_size=4705)
score

[0.60890462663438583, 0.63639154367976714]

### Epoch=50

In [188]:
model = Sequential()
model.add(Dense(50,batch_input_shape=(4705, X_train[:-64].shape[1],X_train[:-64].shape[2]),
               kernel_constraint=maxnorm(1)))
model.add(Dropout(0.2))
model.add(LSTM(45, stateful=True))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',
         optimizer='rmsprop',
         metrics=['accuracy'])

for i in range(50):
    model.fit(X_train[:-64], y_train[:-64], batch_size=4705,shuffle=False, epochs=1,verbose=0)
    model.reset_states()

In [189]:
score = model.evaluate(X_test[:-31], y_test[:-31], verbose=0,batch_size=4705)
score

[0.62619225846396553, 0.63624986012776696]

### Epoch=60

In [186]:
model = Sequential()
model.add(Dense(50,batch_input_shape=(4705, X_train[:-64].shape[1],X_train[:-64].shape[2]),
               kernel_constraint=maxnorm(1)))
model.add(Dropout(0.2))
model.add(LSTM(45, stateful=True))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',
         optimizer='rmsprop',
         metrics=['accuracy'])

for i in range(60):
    model.fit(X_train[:-64], y_train[:-64], batch_size=4705,shuffle=False, epochs=1,verbose=0)
    model.reset_states()

In [187]:
score = model.evaluate(X_test[:-31], y_test[:-31], verbose=0,batch_size=4705)
score

[0.62952608532375764, 0.63724169797367525]