# League of Legends Dataset - Data Wrangling Pt. 2

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
pd.set_option('display.max_columns', None)
%matplotlib inline

In [2]:
df_merged = pd.read_csv('merged_df.csv', index_col=0)
df_merged.head()

,match_id,league,season,year,team_name,red_or_blue_side,result,game_length,top_player,top_champ,jungle_player,jungle_champ,mid_player,mid_champ,adc_player,adc_champ,support_player,support_champ,ban_1,ban_2,ban_3,ban_4,ban_5
0,001a1f289e3bab22,LCK,Summer_Season,2015,ANC,blue,0,38,ikssu,Hecarim,lira,Gragas,Mickey,Vladimir,Sangyoon,Sivir,SnowFlower,Morgana,'Azir','Shyvana','Jayce',NaN,NaN
1,001a1f289e3bab22,LCK,Summer_Season,2015,CJE,red,1,38,Shy,Rumble,Ambition,Sejuani,Coco,Cassiopeia,Space,Jinx,Thresh,MadLife,'Zed','Gnar','Kalista',NaN,NaN
2,001f50c8547e2e73,Season_World_Championship,International,2014,EDG,blue,1,37,Koro1,Maokai,Clearlove,Rengar,U,Zed,NaMei,Twitch,Fzzf,Thresh,'Fizz','LeeSin','TwistedFate',NaN,NaN
3,001f50c8547e2e73,Season_World_Championship,International,2014,AHQ,red,0,37,Prydz,Nidalee,NAZ,Khazix,westdoor,Talon,GarnetDevil,Lucian,Blitzcrank,GreenTea,'Ryze','Zilean','Alistar',NaN,NaN
4,002f613ae09ad421,LMS,Spring_Season,2016,TPA,blue,1,30,Morning,Trundle,REFRA1N,RekSai,FoFo,Lissandra,BeBe,Lucian,Jay,Alistar,'Corki','Gangplank','TahmKench',NaN,NaN

In [3]:
gold_df = pd.read_csv('gold_df_merged.csv', index_col=0)
gold_df.head()

,match_id,league,season,year,team_name,red_or_blue_side,result,game_length,type,player_name,champion,min_0,min_1,min_2,min_3,min_4,min_5,min_6,min_7,min_8,min_9,min_10,min_11,min_12,min_13,min_14,min_15,min_16,min_17,min_18,min_19,min_20,min_21,min_22,min_23,min_24,min_25,min_26,min_27,min_28,min_29,min_30,min_31,min_32,min_33,min_34,min_35,min_36,min_37,min_38,min_39,min_40,min_41,min_42,min_43,min_44,min_45,min_46,min_47,min_48,min_49,min_50,min_51,min_52,min_53,min_54,min_55,min_56,min_57,min_58,min_59,min_60,min_61,min_62,min_63,min_64,min_65,min_66,min_67,min_68,min_69,min_70,min_71,min_72,min_73,min_74,min_75,min_76,min_77,min_78,min_79,min_80
0,001a1f289e3bab22,LCK,Summer_Season,2015,ANC,blue,0,38,total_gold,NaN,NaN,2415,2430,2751,3929,5219,6418,8156,9520,10681,12036,13678,15590,16782,18417,20052,21608,23396,24248,25691,27452.0,30446.0,31672.0,33665.0,36399.0,37571.0,38659.0,39757.0,41498.0,42861.0,44378.0,45719.0,47095.0,48551.0,49524.0,51200.0,52518.0,53247.0,53893.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,001a1f289e3bab22,LCK,Summer_Season,2015,CJE,red,1,38,total_gold,NaN,NaN,2415,2415,2705,4062,5279,7322,8661,10372,11444,13260,14676,15723,18119,19663,21237,22809,24997,28072,30162,31469.0,32490.0,34362.0,36662.0,37981.0,39398.0,40331.0,41652.0,44239.0,45948.0,47134.0,49334.0,51052.0,52586.0,53374.0,55245.0,56618.0,62198.0,62846.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,001f50c8547e2e73,Season_World_Championship,International,2014,EDG,blue,1,37,total_gold,NaN,NaN,2415,2415,2705,3817,4956,6132,7499,8605,9942,11434,13028,15942,17653,19941,21320,23236,24835,26384,29350,32365.0,33752.0,35258.0,39070.0,40973.0,42591.0,45637.0,46672.0,48001.0,49458.0,51181.0,52245.0,54233.0,58476.0,61061.0,62324.0,65435.0,69584.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,001f50c8547e2e73,Season_World_Championship,International,2014,AHQ,red,0,37,total_gold,NaN,NaN,2415,2415,2705,3728,5048,6306,7308,8536,9689,11072,12952,13978,15289,16639,18575,19558,22343,23318,24585,25342.0,26616.0,27778.0,29198.0,30997.0,32647.0,34549.0,35535.0,36591.0,38024.0,39272.0,40585.0,41883.0,42547.0,43836.0,45798.0,46951.0,47804.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,002f613ae09ad421,LMS,Spring_Season,2016,TPA,blue,1,30,total_gold,NaN,NaN,2500,2500,2785,4216,6193,7618,9674,11203,13004,14497,15653,17089,19084,20938,22437,24228,27072,28475,31466,34244.0,37178.0,39046.0,41074.0,42978.0,44964.0,48148.0,49707.0,51624.0,54594.0,56268.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
df_merged = df_merged.reset_index(drop=True)
df_merged.to_csv('merged_df_csv')

In [5]:
gold_df = gold_df.reset_index(drop=True)
gold_df.to_csv('gold_df')

In [6]:
df_merged.tail()

,match_id,league,season,year,team_name,red_or_blue_side,result,game_length,top_player,top_champ,jungle_player,jungle_champ,mid_player,mid_champ,adc_player,adc_champ,support_player,support_champ,ban_1,ban_2,ban_3,ban_4,ban_5
7599,ffee707e7f60869a,LMS,Spring_Season,2016,HKE,red,0,43,MapleSnow,Malphite,Dinter,Gragas,Rokenia,Zed,GodKwai,Corki,Alistar,Olleh,'Nidalee','Kindred','Thresh',NaN,NaN
7600,ffeff6e4c32e9fd0,LCK,Spring_Season,2015,JAG,blue,0,41,TrAce,Maokai,Chaser,JarvanIV,GBM,Karthus,Pilot,Graves,Chei,Annie,'Leblanc','Rumble','Anivia',NaN,NaN
7601,ffeff6e4c32e9fd0,LCK,Spring_Season,2015,SKT,red,1,41,MaRin,Hecarim,Bengi,Sejuani,Faker,Vladimir,Bang,Kalista,Thresh,Wolf,'Lulu','RekSai','Xerath',NaN,NaN
7602,fff9913c8be5e3fd,LCK,Spring_Season,2017,kt,blue,1,45,Smeb,Shen,Score,Khazix,Pawn,Syndra,Deft,Caitlyn,Mata,Zyra,'Malzahar','LeeSin','Varus','Cassiopeia','Taliyah'
7603,fff9913c8be5e3fd,LCK,Spring_Season,2017,JAG,red,0,45,ikssu,Maokai,UmTi,Elise,Kuzan,Corki,Teddy,Ashe,MissFortune,SnowFlower,'Leblanc','Camille','Rengar','Ryze','Jayce'

In [7]:
gold_df.tail()

,match_id,league,season,year,team_name,red_or_blue_side,result,game_length,type,player_name,champion,min_0,min_1,min_2,min_3,min_4,min_5,min_6,min_7,min_8,min_9,min_10,min_11,min_12,min_13,min_14,min_15,min_16,min_17,min_18,min_19,min_20,min_21,min_22,min_23,min_24,min_25,min_26,min_27,min_28,min_29,min_30,min_31,min_32,min_33,min_34,min_35,min_36,min_37,min_38,min_39,min_40,min_41,min_42,min_43,min_44,min_45,min_46,min_47,min_48,min_49,min_50,min_51,min_52,min_53,min_54,min_55,min_56,min_57,min_58,min_59,min_60,min_61,min_62,min_63,min_64,min_65,min_66,min_67,min_68,min_69,min_70,min_71,min_72,min_73,min_74,min_75,min_76,min_77,min_78,min_79,min_80
45619,ffee707e7f60869a,LMS,Spring_Season,2016,HKE,red,0,43,support_gold,Alistar,Olleh,500,500,501,680,1036,1252,1518,1727,1866,2436,2571,2718,2883,3057,3324,3496,3754,3931,4158,4372.0,4633.0,4877.0,5150.0,5354.0,5582.0,5835.0,6090.0,6289.0,6576.0,6758.0,7066.0,7326.0,7839.0,8023.0,8272.0,8545.0,8904.0,9430.0,9620.0,9815.0,9996.0,10519.0,10765.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45620,ffeff6e4c32e9fd0,LCK,Spring_Season,2015,JAG,blue,0,41,support_gold,Chei,Annie,515,515,581,786,961,1123,1301,1442,1792,2045,2197,2488,2624,2795,2941,3086,3742,4002,4784,4919.0,5100.0,5267.0,5492.0,5649.0,5793.0,5959.0,6098.0,6264.0,6424.0,6589.0,6747.0,6903.0,7115.0,7254.0,7389.0,7527.0,7730.0,8522.0,8783.0,8956.0,9230.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45621,ffeff6e4c32e9fd0,LCK,Spring_Season,2015,SKT,red,1,41,support_gold,Thresh,Wolf,515,515,575,742,910,1132,1278,1472,1610,1816,2421,2572,2856,2987,3158,3310,3588,3711,3962,4125.0,4298.0,4436.0,4955.0,5203.0,5379.0,5555.0,5712.0,6294.0,6447.0,7050.0,7342.0,7518.0,7759.0,7972.0,8095.0,8640.0,8763.0,9097.0,9220.0,9441.0,10166.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45622,fff9913c8be5e3fd,LCK,Spring_Season,2017,kt,blue,1,45,support_gold,Mata,Zyra,500,500,550,723,880,1061,1221,1404,1579,1937,2085,2286,2423,2909,3253,3426,3608,3803,4242,4524.0,4751.0,4920.0,5181.0,5382.0,5551.0,5723.0,6287.0,6459.0,6676.0,6880.0,7101.0,7299.0,7578.0,8279.0,8870.0,9093.0,9460.0,9904.0,10138.0,10347.0,10810.0,11091.0,11618.0,11826.0,12628.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45623,fff9913c8be5e3fd,LCK,Spring_Season,2017,JAG,red,0,45,support_gold,MissFortune,SnowFlower,500,524,574,755,912,1085,1265,1499,1682,1875,2078,2326,2492,2775,3044,3206,3821,4029,4241,4553.0,4728.0,4926.0,5255.0,5469.0,5642.0,5857.0,6155.0,6342.0,6548.0,6751.0,6941.0,7202.0,7503.0,7746.0,7923.0,8189.0,8469.0,8760.0,9128.0,9304.0,9670.0,9925.0,10215.0,10470.0,10958.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
gold_df_diff = gold_df.copy()

In [9]:
gold_df_diff.drop(['league', 'season', 'year', 'team_name', 
                   'result', 'game_length', 'type', 'player_name', 'champion'], axis=1, inplace=True)

In [11]:
test_case = gold_df_diff.head(6)
test_case

,match_id,red_or_blue_side,min_0,min_1,min_2,min_3,min_4,min_5,min_6,min_7,min_8,min_9,min_10,min_11,min_12,min_13,min_14,min_15,min_16,min_17,min_18,min_19,min_20,min_21,min_22,min_23,min_24,min_25,min_26,min_27,min_28,min_29,min_30,min_31,min_32,min_33,min_34,min_35,min_36,min_37,min_38,min_39,min_40,min_41,min_42,min_43,min_44,min_45,min_46,min_47,min_48,min_49,min_50,min_51,min_52,min_53,min_54,min_55,min_56,min_57,min_58,min_59,min_60,min_61,min_62,min_63,min_64,min_65,min_66,min_67,min_68,min_69,min_70,min_71,min_72,min_73,min_74,min_75,min_76,min_77,min_78,min_79,min_80
0,001a1f289e3bab22,blue,2415,2430,2751,3929,5219,6418,8156,9520,10681,12036,13678,15590,16782,18417,20052,21608,23396,24248,25691,27452.0,30446.0,31672.0,33665.0,36399.0,37571.0,38659.0,39757.0,41498.0,42861.0,44378.0,45719.0,47095.0,48551.0,49524.0,51200.0,52518.0,53247.0,53893.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,001a1f289e3bab22,red,2415,2415,2705,4062,5279,7322,8661,10372,11444,13260,14676,15723,18119,19663,21237,22809,24997,28072,30162,31469.0,32490.0,34362.0,36662.0,37981.0,39398.0,40331.0,41652.0,44239.0,45948.0,47134.0,49334.0,51052.0,52586.0,53374.0,55245.0,56618.0,62198.0,62846.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,001f50c8547e2e73,blue,2415,2415,2705,3817,4956,6132,7499,8605,9942,11434,13028,15942,17653,19941,21320,23236,24835,26384,29350,32365.0,33752.0,35258.0,39070.0,40973.0,42591.0,45637.0,46672.0,48001.0,49458.0,51181.0,52245.0,54233.0,58476.0,61061.0,62324.0,65435.0,69584.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,001f50c8547e2e73,red,2415,2415,2705,3728,5048,6306,7308,8536,9689,11072,12952,13978,15289,16639,18575,19558,22343,23318,24585,25342.0,26616.0,27778.0,29198.0,30997.0,32647.0,34549.0,35535.0,36591.0,38024.0,39272.0,40585.0,41883.0,42547.0,43836.0,45798.0,46951.0,47804.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,002f613ae09ad421,blue,2500,2500,2785,4216,6193,7618,9674,11203,13004,14497,15653,17089,19084,20938,22437,24228,27072,28475,31466,34244.0,37178.0,39046.0,41074.0,42978.0,44964.0,48148.0,49707.0,51624.0,54594.0,56268.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,002f613ae09ad421,red,2500,2500,2768,4322,6329,7218,9311,10374,11472,12635,14180,15575,16794,18145,19462,20731,21681,23287,24528,25703.0,27343.0,28618.0,29914.0,31486.0,32780.0,33901.0,35335.0,37030.0,38412.0,39924.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [226]:
test_case.to_csv('test_case.csv')

In [215]:
len(gold_df_diff)

45624

In [216]:
red_totals = gold_df_diff.loc[gold_df_diff['red_or_blue_side'] == 'red']
red_totals.head()

,match_id,red_or_blue_side,min_0,min_1,min_2,min_3,min_4,min_5,min_6,min_7,min_8,min_9,min_10,min_11,min_12,min_13,min_14,min_15,min_16,min_17,min_18,min_19,min_20,min_21,min_22,min_23,min_24,min_25,min_26,min_27,min_28,min_29,min_30,min_31,min_32,min_33,min_34,min_35,min_36,min_37,min_38,min_39,min_40,min_41,min_42,min_43,min_44,min_45,min_46,min_47,min_48,min_49,min_50,min_51,min_52,min_53,min_54,min_55,min_56,min_57,min_58,min_59,min_60,min_61,min_62,min_63,min_64,min_65,min_66,min_67,min_68,min_69,min_70,min_71,min_72,min_73,min_74,min_75,min_76,min_77,min_78,min_79,min_80
1,001a1f289e3bab22,red,2415,2415,2705,4062,5279,7322,8661,10372,11444,13260,14676,15723,18119,19663,21237,22809,24997,28072,30162,31469.0,32490.0,34362.0,36662.0,37981.0,39398.0,40331.0,41652.0,44239.0,45948.0,47134.0,49334.0,51052.0,52586.0,53374.0,55245.0,56618.0,62198.0,62846.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,001f50c8547e2e73,red,2415,2415,2705,3728,5048,6306,7308,8536,9689,11072,12952,13978,15289,16639,18575,19558,22343,23318,24585,25342.0,26616.0,27778.0,29198.0,30997.0,32647.0,34549.0,35535.0,36591.0,38024.0,39272.0,40585.0,41883.0,42547.0,43836.0,45798.0,46951.0,47804.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,002f613ae09ad421,red,2500,2500,2768,4322,6329,7218,9311,10374,11472,12635,14180,15575,16794,18145,19462,20731,21681,23287,24528,25703.0,27343.0,28618.0,29914.0,31486.0,32780.0,33901.0,35335.0,37030.0,38412.0,39924.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,003aefd58000cbd6,red,2500,2500,2746,4299,5756,7083,8382,9606,11344,12914,14386,15917,18729,20267,22041,24193,25948,27541,29172,30747.0,33105.0,35386.0,36951.0,39541.0,41429.0,43472.0,45450.0,46929.0,50330.0,52096.0,54144.0,57169.0,59107.0,60847.0,62909.0,65306.0,68578.0,70785.0,75348.0,76519.0,78497.0,80089.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,003dba1358cd918a,red,2415,2415,2744,4140,5268,7214,8487,9911,11357,13309,14988,16436,17949,19328,20730,22213,23735,25196,26742,28178.0,29404.0,30738.0,31760.0,33458.0,35035.0,36230.0,37651.0,39420.0,41434.0,42827.0,43876.0,45032.0,46173.0,47394.0,48316.0,49345.0,50892.0,53012.0,54122.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [217]:
len(red_totals)

22812

In [218]:
blue_totals = gold_df_diff.loc[gold_df_diff['red_or_blue_side'] == 'blue']
blue_totals.head()

,match_id,red_or_blue_side,min_0,min_1,min_2,min_3,min_4,min_5,min_6,min_7,min_8,min_9,min_10,min_11,min_12,min_13,min_14,min_15,min_16,min_17,min_18,min_19,min_20,min_21,min_22,min_23,min_24,min_25,min_26,min_27,min_28,min_29,min_30,min_31,min_32,min_33,min_34,min_35,min_36,min_37,min_38,min_39,min_40,min_41,min_42,min_43,min_44,min_45,min_46,min_47,min_48,min_49,min_50,min_51,min_52,min_53,min_54,min_55,min_56,min_57,min_58,min_59,min_60,min_61,min_62,min_63,min_64,min_65,min_66,min_67,min_68,min_69,min_70,min_71,min_72,min_73,min_74,min_75,min_76,min_77,min_78,min_79,min_80
0,001a1f289e3bab22,blue,2415,2430,2751,3929,5219,6418,8156,9520,10681,12036,13678,15590,16782,18417,20052,21608,23396,24248,25691,27452.0,30446.0,31672.0,33665.0,36399.0,37571.0,38659.0,39757.0,41498.0,42861.0,44378.0,45719.0,47095.0,48551.0,49524.0,51200.0,52518.0,53247.0,53893.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,001f50c8547e2e73,blue,2415,2415,2705,3817,4956,6132,7499,8605,9942,11434,13028,15942,17653,19941,21320,23236,24835,26384,29350,32365.0,33752.0,35258.0,39070.0,40973.0,42591.0,45637.0,46672.0,48001.0,49458.0,51181.0,52245.0,54233.0,58476.0,61061.0,62324.0,65435.0,69584.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,002f613ae09ad421,blue,2500,2500,2785,4216,6193,7618,9674,11203,13004,14497,15653,17089,19084,20938,22437,24228,27072,28475,31466,34244.0,37178.0,39046.0,41074.0,42978.0,44964.0,48148.0,49707.0,51624.0,54594.0,56268.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,003aefd58000cbd6,blue,2500,2518,2784,4204,5649,7170,8559,9953,11663,12714,14296,15798,17515,18823,20595,21962,23723,25555,27452,28762.0,31470.0,32819.0,34832.0,36892.0,38664.0,40433.0,42157.0,43795.0,45126.0,47277.0,49057.0,50573.0,52481.0,55047.0,57130.0,58328.0,61234.0,62994.0,64424.0,66861.0,68433.0,70138.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,003dba1358cd918a,blue,2415,2415,2720,4009,5217,7079,8140,9381,10636,12473,13906,15445,16376,18146,19117,20696,22036,23296,24619,26054.0,27522.0,29390.0,31516.0,32711.0,34324.0,35482.0,37114.0,38794.0,40597.0,42839.0,44927.0,46576.0,48175.0,49751.0,51104.0,53077.0,54001.0,57370.0,61391.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [220]:
blue_totals.values() - red_totals.values()

TypeError: 'numpy.ndarray' object is not callable

In [221]:
gold_df_diff.head()

,match_id,red_or_blue_side,min_0,min_1,min_2,min_3,min_4,min_5,min_6,min_7,min_8,min_9,min_10,min_11,min_12,min_13,min_14,min_15,min_16,min_17,min_18,min_19,min_20,min_21,min_22,min_23,min_24,min_25,min_26,min_27,min_28,min_29,min_30,min_31,min_32,min_33,min_34,min_35,min_36,min_37,min_38,min_39,min_40,min_41,min_42,min_43,min_44,min_45,min_46,min_47,min_48,min_49,min_50,min_51,min_52,min_53,min_54,min_55,min_56,min_57,min_58,min_59,min_60,min_61,min_62,min_63,min_64,min_65,min_66,min_67,min_68,min_69,min_70,min_71,min_72,min_73,min_74,min_75,min_76,min_77,min_78,min_79,min_80
0,001a1f289e3bab22,blue,2415,2430,2751,3929,5219,6418,8156,9520,10681,12036,13678,15590,16782,18417,20052,21608,23396,24248,25691,27452.0,30446.0,31672.0,33665.0,36399.0,37571.0,38659.0,39757.0,41498.0,42861.0,44378.0,45719.0,47095.0,48551.0,49524.0,51200.0,52518.0,53247.0,53893.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,001a1f289e3bab22,red,2415,2415,2705,4062,5279,7322,8661,10372,11444,13260,14676,15723,18119,19663,21237,22809,24997,28072,30162,31469.0,32490.0,34362.0,36662.0,37981.0,39398.0,40331.0,41652.0,44239.0,45948.0,47134.0,49334.0,51052.0,52586.0,53374.0,55245.0,56618.0,62198.0,62846.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,001f50c8547e2e73,blue,2415,2415,2705,3817,4956,6132,7499,8605,9942,11434,13028,15942,17653,19941,21320,23236,24835,26384,29350,32365.0,33752.0,35258.0,39070.0,40973.0,42591.0,45637.0,46672.0,48001.0,49458.0,51181.0,52245.0,54233.0,58476.0,61061.0,62324.0,65435.0,69584.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,001f50c8547e2e73,red,2415,2415,2705,3728,5048,6306,7308,8536,9689,11072,12952,13978,15289,16639,18575,19558,22343,23318,24585,25342.0,26616.0,27778.0,29198.0,30997.0,32647.0,34549.0,35535.0,36591.0,38024.0,39272.0,40585.0,41883.0,42547.0,43836.0,45798.0,46951.0,47804.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,002f613ae09ad421,blue,2500,2500,2785,4216,6193,7618,9674,11203,13004,14497,15653,17089,19084,20938,22437,24228,27072,28475,31466,34244.0,37178.0,39046.0,41074.0,42978.0,44964.0,48148.0,49707.0,51624.0,54594.0,56268.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [207]:
gold_df_diff.drop(['match_id', 'red_or_blue_side'], inplace=True, axis=1)

In [208]:
red_side = (gold_df_diff - gold_df_diff.shift(1))
red_side.head()

,min_0,min_1,min_2,min_3,min_4,min_5,min_6,min_7,min_8,min_9,min_10,min_11,min_12,min_13,min_14,min_15,min_16,min_17,min_18,min_19,min_20,min_21,min_22,min_23,min_24,min_25,min_26,min_27,min_28,min_29,min_30,min_31,min_32,min_33,min_34,min_35,min_36,min_37,min_38,min_39,min_40,min_41,min_42,min_43,min_44,min_45,min_46,min_47,min_48,min_49,min_50,min_51,min_52,min_53,min_54,min_55,min_56,min_57,min_58,min_59,min_60,min_61,min_62,min_63,min_64,min_65,min_66,min_67,min_68,min_69,min_70,min_71,min_72,min_73,min_74,min_75,min_76,min_77,min_78,min_79,min_80
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0.0,-15.0,-46.0,133.0,60.0,904.0,505.0,852.0,763.0,1224.0,998.0,133.0,1337.0,1246.0,1185.0,1201.0,1601.0,3824.0,4471.0,4017.0,2044.0,2690.0,2997.0,1582.0,1827.0,1672.0,1895.0,2741.0,3087.0,2756.0,3615.0,3957.0,4035.0,3850.0,4045.0,4100.0,8951.0,8953.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0.0,0.0,0.0,-245.0,-323.0,-1190.0,-1162.0,-1767.0,-1502.0,-1826.0,-1648.0,219.0,-466.0,278.0,83.0,427.0,-162.0,-1688.0,-812.0,896.0,1262.0,896.0,2408.0,2992.0,3193.0,5306.0,5020.0,3762.0,3510.0,4047.0,2911.0,3181.0,5890.0,7687.0,7079.0,8817.0,7386.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0.0,0.0,0.0,-89.0,92.0,174.0,-191.0,-69.0,-253.0,-362.0,-76.0,-1964.0,-2364.0,-3302.0,-2745.0,-3678.0,-2492.0,-3066.0,-4765.0,-7023.0,-7136.0,-7480.0,-9872.0,-9976.0,-9944.0,-11088.0,-11137.0,-11410.0,-11434.0,-11909.0,-11660.0,-12350.0,-15929.0,-17225.0,-16526.0,-18484.0,-21780.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,85.0,85.0,80.0,488.0,1145.0,1312.0,2366.0,2667.0,3315.0,3425.0,2701.0,3111.0,3795.0,4299.0,3862.0,4670.0,4729.0,5157.0,6881.0,8902.0,10562.0,11268.0,11876.0,11981.0,12317.0,13599.0,14172.0,15033.0,16570.0,16996.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [209]:
blue_side = (gold_df_diff - gold_df_diff.shift(-1))
blue_side.head()

,min_0,min_1,min_2,min_3,min_4,min_5,min_6,min_7,min_8,min_9,min_10,min_11,min_12,min_13,min_14,min_15,min_16,min_17,min_18,min_19,min_20,min_21,min_22,min_23,min_24,min_25,min_26,min_27,min_28,min_29,min_30,min_31,min_32,min_33,min_34,min_35,min_36,min_37,min_38,min_39,min_40,min_41,min_42,min_43,min_44,min_45,min_46,min_47,min_48,min_49,min_50,min_51,min_52,min_53,min_54,min_55,min_56,min_57,min_58,min_59,min_60,min_61,min_62,min_63,min_64,min_65,min_66,min_67,min_68,min_69,min_70,min_71,min_72,min_73,min_74,min_75,min_76,min_77,min_78,min_79,min_80
0,0.0,15.0,46.0,-133.0,-60.0,-904.0,-505.0,-852.0,-763.0,-1224.0,-998.0,-133.0,-1337.0,-1246.0,-1185.0,-1201.0,-1601.0,-3824.0,-4471.0,-4017.0,-2044.0,-2690.0,-2997.0,-1582.0,-1827.0,-1672.0,-1895.0,-2741.0,-3087.0,-2756.0,-3615.0,-3957.0,-4035.0,-3850.0,-4045.0,-4100.0,-8951.0,-8953.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0.0,0.0,0.0,245.0,323.0,1190.0,1162.0,1767.0,1502.0,1826.0,1648.0,-219.0,466.0,-278.0,-83.0,-427.0,162.0,1688.0,812.0,-896.0,-1262.0,-896.0,-2408.0,-2992.0,-3193.0,-5306.0,-5020.0,-3762.0,-3510.0,-4047.0,-2911.0,-3181.0,-5890.0,-7687.0,-7079.0,-8817.0,-7386.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0.0,0.0,0.0,89.0,-92.0,-174.0,191.0,69.0,253.0,362.0,76.0,1964.0,2364.0,3302.0,2745.0,3678.0,2492.0,3066.0,4765.0,7023.0,7136.0,7480.0,9872.0,9976.0,9944.0,11088.0,11137.0,11410.0,11434.0,11909.0,11660.0,12350.0,15929.0,17225.0,16526.0,18484.0,21780.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,-85.0,-85.0,-80.0,-488.0,-1145.0,-1312.0,-2366.0,-2667.0,-3315.0,-3425.0,-2701.0,-3111.0,-3795.0,-4299.0,-3862.0,-4670.0,-4729.0,-5157.0,-6881.0,-8902.0,-10562.0,-11268.0,-11876.0,-11981.0,-12317.0,-13599.0,-14172.0,-15033.0,-16570.0,-16996.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0.0,0.0,17.0,-106.0,-136.0,400.0,363.0,829.0,1532.0,1862.0,1473.0,1514.0,2290.0,2793.0,2975.0,3497.0,5391.0,5188.0,6938.0,8541.0,9835.0,10428.0,11160.0,11492.0,12184.0,14247.0,14372.0,14594.0,16182.0,16344.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [113]:
red_or_blue = gold_df[['red_or_blue_side', 'result']]
red_or_blue.head()

  red_or_blue_side  result
0             blue       0
1              red       1
2             blue       1
3              red       0
4             blue       1

In [114]:
red_side = red_side.reset_index(drop=True)
red_side = red_side.reset_index()
red_side.head()

,index,min_0,min_1,min_2,min_3,min_4,min_5,min_6,min_7,min_8,min_9,min_10,min_11,min_12,min_13,min_14,min_15,min_16,min_17,min_18,min_19,min_20,min_21,min_22,min_23,min_24,min_25,min_26,min_27,min_28,min_29,min_30,min_31,min_32,min_33,min_34,min_35,min_36,min_37,min_38,min_39,min_40,min_41,min_42,min_43,min_44,min_45,min_46,min_47,min_48,min_49,min_50,min_51,min_52,min_53,min_54,min_55,min_56,min_57,min_58,min_59,min_60,min_61,min_62,min_63,min_64,min_65,min_66,min_67,min_68,min_69,min_70,min_71,min_72,min_73,min_74,min_75,min_76,min_77,min_78,min_79,min_80
0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,0.0,-15.0,-46.0,133.0,60.0,904.0,505.0,852.0,763.0,1224.0,998.0,133.0,1337.0,1246.0,1185.0,1201.0,1601.0,3824.0,4471.0,4017.0,2044.0,2690.0,2997.0,1582.0,1827.0,1672.0,1895.0,2741.0,3087.0,2756.0,3615.0,3957.0,4035.0,3850.0,4045.0,4100.0,8951.0,8953.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,0.0,0.0,0.0,-245.0,-323.0,-1190.0,-1162.0,-1767.0,-1502.0,-1826.0,-1648.0,219.0,-466.0,278.0,83.0,427.0,-162.0,-1688.0,-812.0,896.0,1262.0,896.0,2408.0,2992.0,3193.0,5306.0,5020.0,3762.0,3510.0,4047.0,2911.0,3181.0,5890.0,7687.0,7079.0,8817.0,7386.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,0.0,0.0,0.0,-89.0,92.0,174.0,-191.0,-69.0,-253.0,-362.0,-76.0,-1964.0,-2364.0,-3302.0,-2745.0,-3678.0,-2492.0,-3066.0,-4765.0,-7023.0,-7136.0,-7480.0,-9872.0,-9976.0,-9944.0,-11088.0,-11137.0,-11410.0,-11434.0,-11909.0,-11660.0,-12350.0,-15929.0,-17225.0,-16526.0,-18484.0,-21780.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,85.0,85.0,80.0,488.0,1145.0,1312.0,2366.0,2667.0,3315.0,3425.0,2701.0,3111.0,3795.0,4299.0,3862.0,4670.0,4729.0,5157.0,6881.0,8902.0,10562.0,11268.0,11876.0,11981.0,12317.0,13599.0,14172.0,15033.0,16570.0,16996.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [116]:
red_or_blue = red_or_blue.reset_index(drop=True)
red_or_blue = red_or_blue.reset_index()
red_or_blue.head()

   index red_or_blue_side  result
0      0             blue       0
1      1              red       1
2      2             blue       1
3      3              red       0
4      4             blue       1

In [117]:
print(red_or_blue['index'].max())
print(red_side['index'].max())

45623
45623

In [119]:
merged_red = pd.merge(red_or_blue, red_side, on='index')
merged_red.head()

,index,red_or_blue_side,result,min_0,min_1,min_2,min_3,min_4,min_5,min_6,min_7,min_8,min_9,min_10,min_11,min_12,min_13,min_14,min_15,min_16,min_17,min_18,min_19,min_20,min_21,min_22,min_23,min_24,min_25,min_26,min_27,min_28,min_29,min_30,min_31,min_32,min_33,min_34,min_35,min_36,min_37,min_38,min_39,min_40,min_41,min_42,min_43,min_44,min_45,min_46,min_47,min_48,min_49,min_50,min_51,min_52,min_53,min_54,min_55,min_56,min_57,min_58,min_59,min_60,min_61,min_62,min_63,min_64,min_65,min_66,min_67,min_68,min_69,min_70,min_71,min_72,min_73,min_74,min_75,min_76,min_77,min_78,min_79,min_80
0,0,blue,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,red,1,0.0,-15.0,-46.0,133.0,60.0,904.0,505.0,852.0,763.0,1224.0,998.0,133.0,1337.0,1246.0,1185.0,1201.0,1601.0,3824.0,4471.0,4017.0,2044.0,2690.0,2997.0,1582.0,1827.0,1672.0,1895.0,2741.0,3087.0,2756.0,3615.0,3957.0,4035.0,3850.0,4045.0,4100.0,8951.0,8953.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,blue,1,0.0,0.0,0.0,-245.0,-323.0,-1190.0,-1162.0,-1767.0,-1502.0,-1826.0,-1648.0,219.0,-466.0,278.0,83.0,427.0,-162.0,-1688.0,-812.0,896.0,1262.0,896.0,2408.0,2992.0,3193.0,5306.0,5020.0,3762.0,3510.0,4047.0,2911.0,3181.0,5890.0,7687.0,7079.0,8817.0,7386.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,red,0,0.0,0.0,0.0,-89.0,92.0,174.0,-191.0,-69.0,-253.0,-362.0,-76.0,-1964.0,-2364.0,-3302.0,-2745.0,-3678.0,-2492.0,-3066.0,-4765.0,-7023.0,-7136.0,-7480.0,-9872.0,-9976.0,-9944.0,-11088.0,-11137.0,-11410.0,-11434.0,-11909.0,-11660.0,-12350.0,-15929.0,-17225.0,-16526.0,-18484.0,-21780.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,blue,1,85.0,85.0,80.0,488.0,1145.0,1312.0,2366.0,2667.0,3315.0,3425.0,2701.0,3111.0,3795.0,4299.0,3862.0,4670.0,4729.0,5157.0,6881.0,8902.0,10562.0,11268.0,11876.0,11981.0,12317.0,13599.0,14172.0,15033.0,16570.0,16996.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [120]:
red_or_blue.head()

   index red_or_blue_side  result
0      0             blue       0
1      1              red       1
2      2             blue       1
3      3              red       0
4      4             blue       1

In [122]:
blue_side = blue_side.reset_index(drop=True)
blue_side = blue_side.reset_index()
blue_side.head()

,index,min_0,min_1,min_2,min_3,min_4,min_5,min_6,min_7,min_8,min_9,min_10,min_11,min_12,min_13,min_14,min_15,min_16,min_17,min_18,min_19,min_20,min_21,min_22,min_23,min_24,min_25,min_26,min_27,min_28,min_29,min_30,min_31,min_32,min_33,min_34,min_35,min_36,min_37,min_38,min_39,min_40,min_41,min_42,min_43,min_44,min_45,min_46,min_47,min_48,min_49,min_50,min_51,min_52,min_53,min_54,min_55,min_56,min_57,min_58,min_59,min_60,min_61,min_62,min_63,min_64,min_65,min_66,min_67,min_68,min_69,min_70,min_71,min_72,min_73,min_74,min_75,min_76,min_77,min_78,min_79,min_80
0,0,0.0,15.0,46.0,-133.0,-60.0,-904.0,-505.0,-852.0,-763.0,-1224.0,-998.0,-133.0,-1337.0,-1246.0,-1185.0,-1201.0,-1601.0,-3824.0,-4471.0,-4017.0,-2044.0,-2690.0,-2997.0,-1582.0,-1827.0,-1672.0,-1895.0,-2741.0,-3087.0,-2756.0,-3615.0,-3957.0,-4035.0,-3850.0,-4045.0,-4100.0,-8951.0,-8953.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,0.0,0.0,0.0,245.0,323.0,1190.0,1162.0,1767.0,1502.0,1826.0,1648.0,-219.0,466.0,-278.0,-83.0,-427.0,162.0,1688.0,812.0,-896.0,-1262.0,-896.0,-2408.0,-2992.0,-3193.0,-5306.0,-5020.0,-3762.0,-3510.0,-4047.0,-2911.0,-3181.0,-5890.0,-7687.0,-7079.0,-8817.0,-7386.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,0.0,0.0,0.0,89.0,-92.0,-174.0,191.0,69.0,253.0,362.0,76.0,1964.0,2364.0,3302.0,2745.0,3678.0,2492.0,3066.0,4765.0,7023.0,7136.0,7480.0,9872.0,9976.0,9944.0,11088.0,11137.0,11410.0,11434.0,11909.0,11660.0,12350.0,15929.0,17225.0,16526.0,18484.0,21780.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,-85.0,-85.0,-80.0,-488.0,-1145.0,-1312.0,-2366.0,-2667.0,-3315.0,-3425.0,-2701.0,-3111.0,-3795.0,-4299.0,-3862.0,-4670.0,-4729.0,-5157.0,-6881.0,-8902.0,-10562.0,-11268.0,-11876.0,-11981.0,-12317.0,-13599.0,-14172.0,-15033.0,-16570.0,-16996.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,0.0,0.0,17.0,-106.0,-136.0,400.0,363.0,829.0,1532.0,1862.0,1473.0,1514.0,2290.0,2793.0,2975.0,3497.0,5391.0,5188.0,6938.0,8541.0,9835.0,10428.0,11160.0,11492.0,12184.0,14247.0,14372.0,14594.0,16182.0,16344.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [123]:
print(red_or_blue['index'].max())
print(blue_side['index'].max())

45623
45623

In [124]:
merged_blue = pd.merge(red_or_blue, blue_side, on='index')
merged_blue.head()

,index,red_or_blue_side,result,min_0,min_1,min_2,min_3,min_4,min_5,min_6,min_7,min_8,min_9,min_10,min_11,min_12,min_13,min_14,min_15,min_16,min_17,min_18,min_19,min_20,min_21,min_22,min_23,min_24,min_25,min_26,min_27,min_28,min_29,min_30,min_31,min_32,min_33,min_34,min_35,min_36,min_37,min_38,min_39,min_40,min_41,min_42,min_43,min_44,min_45,min_46,min_47,min_48,min_49,min_50,min_51,min_52,min_53,min_54,min_55,min_56,min_57,min_58,min_59,min_60,min_61,min_62,min_63,min_64,min_65,min_66,min_67,min_68,min_69,min_70,min_71,min_72,min_73,min_74,min_75,min_76,min_77,min_78,min_79,min_80
0,0,blue,0,0.0,15.0,46.0,-133.0,-60.0,-904.0,-505.0,-852.0,-763.0,-1224.0,-998.0,-133.0,-1337.0,-1246.0,-1185.0,-1201.0,-1601.0,-3824.0,-4471.0,-4017.0,-2044.0,-2690.0,-2997.0,-1582.0,-1827.0,-1672.0,-1895.0,-2741.0,-3087.0,-2756.0,-3615.0,-3957.0,-4035.0,-3850.0,-4045.0,-4100.0,-8951.0,-8953.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,red,1,0.0,0.0,0.0,245.0,323.0,1190.0,1162.0,1767.0,1502.0,1826.0,1648.0,-219.0,466.0,-278.0,-83.0,-427.0,162.0,1688.0,812.0,-896.0,-1262.0,-896.0,-2408.0,-2992.0,-3193.0,-5306.0,-5020.0,-3762.0,-3510.0,-4047.0,-2911.0,-3181.0,-5890.0,-7687.0,-7079.0,-8817.0,-7386.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,blue,1,0.0,0.0,0.0,89.0,-92.0,-174.0,191.0,69.0,253.0,362.0,76.0,1964.0,2364.0,3302.0,2745.0,3678.0,2492.0,3066.0,4765.0,7023.0,7136.0,7480.0,9872.0,9976.0,9944.0,11088.0,11137.0,11410.0,11434.0,11909.0,11660.0,12350.0,15929.0,17225.0,16526.0,18484.0,21780.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,red,0,-85.0,-85.0,-80.0,-488.0,-1145.0,-1312.0,-2366.0,-2667.0,-3315.0,-3425.0,-2701.0,-3111.0,-3795.0,-4299.0,-3862.0,-4670.0,-4729.0,-5157.0,-6881.0,-8902.0,-10562.0,-11268.0,-11876.0,-11981.0,-12317.0,-13599.0,-14172.0,-15033.0,-16570.0,-16996.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,blue,1,0.0,0.0,17.0,-106.0,-136.0,400.0,363.0,829.0,1532.0,1862.0,1473.0,1514.0,2290.0,2793.0,2975.0,3497.0,5391.0,5188.0,6938.0,8541.0,9835.0,10428.0,11160.0,11492.0,12184.0,14247.0,14372.0,14594.0,16182.0,16344.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [125]:
merged_blue = merged_blue.loc[merged_blue['red_or_blue_side'] == 'blue']
merged_blue.head()

,index,red_or_blue_side,result,min_0,min_1,min_2,min_3,min_4,min_5,min_6,min_7,min_8,min_9,min_10,min_11,min_12,min_13,min_14,min_15,min_16,min_17,min_18,min_19,min_20,min_21,min_22,min_23,min_24,min_25,min_26,min_27,min_28,min_29,min_30,min_31,min_32,min_33,min_34,min_35,min_36,min_37,min_38,min_39,min_40,min_41,min_42,min_43,min_44,min_45,min_46,min_47,min_48,min_49,min_50,min_51,min_52,min_53,min_54,min_55,min_56,min_57,min_58,min_59,min_60,min_61,min_62,min_63,min_64,min_65,min_66,min_67,min_68,min_69,min_70,min_71,min_72,min_73,min_74,min_75,min_76,min_77,min_78,min_79,min_80
0,0,blue,0,0.0,15.0,46.0,-133.0,-60.0,-904.0,-505.0,-852.0,-763.0,-1224.0,-998.0,-133.0,-1337.0,-1246.0,-1185.0,-1201.0,-1601.0,-3824.0,-4471.0,-4017.0,-2044.0,-2690.0,-2997.0,-1582.0,-1827.0,-1672.0,-1895.0,-2741.0,-3087.0,-2756.0,-3615.0,-3957.0,-4035.0,-3850.0,-4045.0,-4100.0,-8951.0,-8953.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,blue,1,0.0,0.0,0.0,89.0,-92.0,-174.0,191.0,69.0,253.0,362.0,76.0,1964.0,2364.0,3302.0,2745.0,3678.0,2492.0,3066.0,4765.0,7023.0,7136.0,7480.0,9872.0,9976.0,9944.0,11088.0,11137.0,11410.0,11434.0,11909.0,11660.0,12350.0,15929.0,17225.0,16526.0,18484.0,21780.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,blue,1,0.0,0.0,17.0,-106.0,-136.0,400.0,363.0,829.0,1532.0,1862.0,1473.0,1514.0,2290.0,2793.0,2975.0,3497.0,5391.0,5188.0,6938.0,8541.0,9835.0,10428.0,11160.0,11492.0,12184.0,14247.0,14372.0,14594.0,16182.0,16344.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,7,blue,0,85.0,103.0,40.0,64.0,381.0,-44.0,72.0,42.0,306.0,-595.0,-692.0,-638.0,-434.0,-505.0,-135.0,-251.0,-12.0,359.0,710.0,584.0,2066.0,2081.0,3072.0,3434.0,3629.0,4203.0,4506.0,4375.0,3692.0,4450.0,5181.0,5541.0,6308.0,7653.0,8814.0,8983.0,10342.0,9982.0,10302.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,9,blue,1,-85.0,-85.0,-46.0,-118.0,-1018.0,-518.0,-1441.0,-1443.0,-1908.0,-1171.0,-1309.0,-1085.0,-1581.0,-1437.0,-1852.0,-1613.0,-2615.0,-2914.0,-2960.0,-3219.0,-3225.0,-2986.0,-2238.0,-2610.0,-2213.0,-2156.0,-2066.0,-1376.0,-1611.0,-662.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [126]:
merged_red = merged_red.loc[merged_red['red_or_blue_side'] == 'red']
merged_red.head()

,index,red_or_blue_side,result,min_0,min_1,min_2,min_3,min_4,min_5,min_6,min_7,min_8,min_9,min_10,min_11,min_12,min_13,min_14,min_15,min_16,min_17,min_18,min_19,min_20,min_21,min_22,min_23,min_24,min_25,min_26,min_27,min_28,min_29,min_30,min_31,min_32,min_33,min_34,min_35,min_36,min_37,min_38,min_39,min_40,min_41,min_42,min_43,min_44,min_45,min_46,min_47,min_48,min_49,min_50,min_51,min_52,min_53,min_54,min_55,min_56,min_57,min_58,min_59,min_60,min_61,min_62,min_63,min_64,min_65,min_66,min_67,min_68,min_69,min_70,min_71,min_72,min_73,min_74,min_75,min_76,min_77,min_78,min_79,min_80
1,1,red,1,0.0,-15.0,-46.0,133.0,60.0,904.0,505.0,852.0,763.0,1224.0,998.0,133.0,1337.0,1246.0,1185.0,1201.0,1601.0,3824.0,4471.0,4017.0,2044.0,2690.0,2997.0,1582.0,1827.0,1672.0,1895.0,2741.0,3087.0,2756.0,3615.0,3957.0,4035.0,3850.0,4045.0,4100.0,8951.0,8953.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,red,0,0.0,0.0,0.0,-89.0,92.0,174.0,-191.0,-69.0,-253.0,-362.0,-76.0,-1964.0,-2364.0,-3302.0,-2745.0,-3678.0,-2492.0,-3066.0,-4765.0,-7023.0,-7136.0,-7480.0,-9872.0,-9976.0,-9944.0,-11088.0,-11137.0,-11410.0,-11434.0,-11909.0,-11660.0,-12350.0,-15929.0,-17225.0,-16526.0,-18484.0,-21780.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,5,red,0,0.0,0.0,-17.0,106.0,136.0,-400.0,-363.0,-829.0,-1532.0,-1862.0,-1473.0,-1514.0,-2290.0,-2793.0,-2975.0,-3497.0,-5391.0,-5188.0,-6938.0,-8541.0,-9835.0,-10428.0,-11160.0,-11492.0,-12184.0,-14247.0,-14372.0,-14594.0,-16182.0,-16344.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,6,red,1,0.0,0.0,-22.0,-23.0,-573.0,-135.0,-929.0,-768.0,-128.0,279.0,206.0,342.0,1935.0,2122.0,2579.0,3462.0,4267.0,4254.0,4644.0,5044.0,5762.0,6768.0,7037.0,8055.0,8649.0,9571.0,10115.0,9899.0,11918.0,12172.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,8,red,0,-85.0,-103.0,-40.0,-64.0,-381.0,44.0,-72.0,-42.0,-306.0,595.0,692.0,638.0,434.0,505.0,135.0,251.0,12.0,-359.0,-710.0,-584.0,-2066.0,-2081.0,-3072.0,-3434.0,-3629.0,-4203.0,-4506.0,-4375.0,-3692.0,-4450.0,-5181.0,-5541.0,-6308.0,-7653.0,-8814.0,-8983.0,-10342.0,-9982.0,-10302.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [129]:
merged_redandblue = pd.concat([merged_blue, merged_red])
merged_gold_diff = merged_redandblue.sort_values(by='index')
merged_gold_diff.head()

,index,red_or_blue_side,result,min_0,min_1,min_2,min_3,min_4,min_5,min_6,min_7,min_8,min_9,min_10,min_11,min_12,min_13,min_14,min_15,min_16,min_17,min_18,min_19,min_20,min_21,min_22,min_23,min_24,min_25,min_26,min_27,min_28,min_29,min_30,min_31,min_32,min_33,min_34,min_35,min_36,min_37,min_38,min_39,min_40,min_41,min_42,min_43,min_44,min_45,min_46,min_47,min_48,min_49,min_50,min_51,min_52,min_53,min_54,min_55,min_56,min_57,min_58,min_59,min_60,min_61,min_62,min_63,min_64,min_65,min_66,min_67,min_68,min_69,min_70,min_71,min_72,min_73,min_74,min_75,min_76,min_77,min_78,min_79,min_80
0,0,blue,0,0.0,15.0,46.0,-133.0,-60.0,-904.0,-505.0,-852.0,-763.0,-1224.0,-998.0,-133.0,-1337.0,-1246.0,-1185.0,-1201.0,-1601.0,-3824.0,-4471.0,-4017.0,-2044.0,-2690.0,-2997.0,-1582.0,-1827.0,-1672.0,-1895.0,-2741.0,-3087.0,-2756.0,-3615.0,-3957.0,-4035.0,-3850.0,-4045.0,-4100.0,-8951.0,-8953.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,red,1,0.0,-15.0,-46.0,133.0,60.0,904.0,505.0,852.0,763.0,1224.0,998.0,133.0,1337.0,1246.0,1185.0,1201.0,1601.0,3824.0,4471.0,4017.0,2044.0,2690.0,2997.0,1582.0,1827.0,1672.0,1895.0,2741.0,3087.0,2756.0,3615.0,3957.0,4035.0,3850.0,4045.0,4100.0,8951.0,8953.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,blue,1,0.0,0.0,0.0,89.0,-92.0,-174.0,191.0,69.0,253.0,362.0,76.0,1964.0,2364.0,3302.0,2745.0,3678.0,2492.0,3066.0,4765.0,7023.0,7136.0,7480.0,9872.0,9976.0,9944.0,11088.0,11137.0,11410.0,11434.0,11909.0,11660.0,12350.0,15929.0,17225.0,16526.0,18484.0,21780.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,red,0,0.0,0.0,0.0,-89.0,92.0,174.0,-191.0,-69.0,-253.0,-362.0,-76.0,-1964.0,-2364.0,-3302.0,-2745.0,-3678.0,-2492.0,-3066.0,-4765.0,-7023.0,-7136.0,-7480.0,-9872.0,-9976.0,-9944.0,-11088.0,-11137.0,-11410.0,-11434.0,-11909.0,-11660.0,-12350.0,-15929.0,-17225.0,-16526.0,-18484.0,-21780.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,blue,1,0.0,0.0,17.0,-106.0,-136.0,400.0,363.0,829.0,1532.0,1862.0,1473.0,1514.0,2290.0,2793.0,2975.0,3497.0,5391.0,5188.0,6938.0,8541.0,9835.0,10428.0,11160.0,11492.0,12184.0,14247.0,14372.0,14594.0,16182.0,16344.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [137]:
cols = list(gold_df.columns.values)
cols = ['match_id', 'league', 'season', 'year', 'team_name', 'red_or_blue_side', 'result',
        'game_length', 'type', 'player_name', 'champion']
gold_df1 = gold_df[cols]
gold_df1.head()

,match_id,league,season,year,team_name,red_or_blue_side,result,game_length,type,player_name,champion
0,001a1f289e3bab22,LCK,Summer_Season,2015,ANC,blue,0,38,total_gold,NaN,NaN
1,001a1f289e3bab22,LCK,Summer_Season,2015,CJE,red,1,38,total_gold,NaN,NaN
2,001f50c8547e2e73,Season_World_Championship,International,2014,EDG,blue,1,37,total_gold,NaN,NaN
3,001f50c8547e2e73,Season_World_Championship,International,2014,AHQ,red,0,37,total_gold,NaN,NaN
4,002f613ae09ad421,LMS,Spring_Season,2016,TPA,blue,1,30,total_gold,NaN,NaN

In [139]:
gold_df1 = gold_df1.reset_index(drop=True)
gold_df1 = gold_df1.reset_index()
print(gold_df1['index'].max())
gold_df1.head()

45623

,level_0,index,match_id,league,season,year,team_name,red_or_blue_side,result,game_length,type,player_name,champion
0,0,0,001a1f289e3bab22,LCK,Summer_Season,2015,ANC,blue,0,38,total_gold,NaN,NaN
1,1,1,001a1f289e3bab22,LCK,Summer_Season,2015,CJE,red,1,38,total_gold,NaN,NaN
2,2,2,001f50c8547e2e73,Season_World_Championship,International,2014,EDG,blue,1,37,total_gold,NaN,NaN
3,3,3,001f50c8547e2e73,Season_World_Championship,International,2014,AHQ,red,0,37,total_gold,NaN,NaN
4,4,4,002f613ae09ad421,LMS,Spring_Season,2016,TPA,blue,1,30,total_gold,NaN,NaN

In [140]:
gold_df1.drop(['level_0'],axis=1, inplace=True)
gold_df1.head()

,index,match_id,league,season,year,team_name,red_or_blue_side,result,game_length,type,player_name,champion
0,0,001a1f289e3bab22,LCK,Summer_Season,2015,ANC,blue,0,38,total_gold,NaN,NaN
1,1,001a1f289e3bab22,LCK,Summer_Season,2015,CJE,red,1,38,total_gold,NaN,NaN
2,2,001f50c8547e2e73,Season_World_Championship,International,2014,EDG,blue,1,37,total_gold,NaN,NaN
3,3,001f50c8547e2e73,Season_World_Championship,International,2014,AHQ,red,0,37,total_gold,NaN,NaN
4,4,002f613ae09ad421,LMS,Spring_Season,2016,TPA,blue,1,30,total_gold,NaN,NaN

In [141]:
print(gold_df1['index'].max())

45623

In [142]:
final_gold = pd.merge(gold_df1, merged_gold_diff, on='index')
final_gold.head()

,index,match_id,league,season,year,team_name,red_or_blue_side_x,result_x,game_length,type,player_name,champion,red_or_blue_side_y,result_y,min_0,min_1,min_2,min_3,min_4,min_5,min_6,min_7,min_8,min_9,min_10,min_11,min_12,min_13,min_14,min_15,min_16,min_17,min_18,min_19,min_20,min_21,min_22,min_23,min_24,min_25,min_26,min_27,min_28,min_29,min_30,min_31,min_32,min_33,min_34,min_35,min_36,min_37,min_38,min_39,min_40,min_41,min_42,min_43,min_44,min_45,min_46,min_47,min_48,min_49,min_50,min_51,min_52,min_53,min_54,min_55,min_56,min_57,min_58,min_59,min_60,min_61,min_62,min_63,min_64,min_65,min_66,min_67,min_68,min_69,min_70,min_71,min_72,min_73,min_74,min_75,min_76,min_77,min_78,min_79,min_80
0,0,001a1f289e3bab22,LCK,Summer_Season,2015,ANC,blue,0,38,total_gold,NaN,NaN,blue,0,0.0,15.0,46.0,-133.0,-60.0,-904.0,-505.0,-852.0,-763.0,-1224.0,-998.0,-133.0,-1337.0,-1246.0,-1185.0,-1201.0,-1601.0,-3824.0,-4471.0,-4017.0,-2044.0,-2690.0,-2997.0,-1582.0,-1827.0,-1672.0,-1895.0,-2741.0,-3087.0,-2756.0,-3615.0,-3957.0,-4035.0,-3850.0,-4045.0,-4100.0,-8951.0,-8953.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,001a1f289e3bab22,LCK,Summer_Season,2015,CJE,red,1,38,total_gold,NaN,NaN,red,1,0.0,-15.0,-46.0,133.0,60.0,904.0,505.0,852.0,763.0,1224.0,998.0,133.0,1337.0,1246.0,1185.0,1201.0,1601.0,3824.0,4471.0,4017.0,2044.0,2690.0,2997.0,1582.0,1827.0,1672.0,1895.0,2741.0,3087.0,2756.0,3615.0,3957.0,4035.0,3850.0,4045.0,4100.0,8951.0,8953.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,001f50c8547e2e73,Season_World_Championship,International,2014,EDG,blue,1,37,total_gold,NaN,NaN,blue,1,0.0,0.0,0.0,89.0,-92.0,-174.0,191.0,69.0,253.0,362.0,76.0,1964.0,2364.0,3302.0,2745.0,3678.0,2492.0,3066.0,4765.0,7023.0,7136.0,7480.0,9872.0,9976.0,9944.0,11088.0,11137.0,11410.0,11434.0,11909.0,11660.0,12350.0,15929.0,17225.0,16526.0,18484.0,21780.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,001f50c8547e2e73,Season_World_Championship,International,2014,AHQ,red,0,37,total_gold,NaN,NaN,red,0,0.0,0.0,0.0,-89.0,92.0,174.0,-191.0,-69.0,-253.0,-362.0,-76.0,-1964.0,-2364.0,-3302.0,-2745.0,-3678.0,-2492.0,-3066.0,-4765.0,-7023.0,-7136.0,-7480.0,-9872.0,-9976.0,-9944.0,-11088.0,-11137.0,-11410.0,-11434.0,-11909.0,-11660.0,-12350.0,-15929.0,-17225.0,-16526.0,-18484.0,-21780.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,002f613ae09ad421,LMS,Spring_Season,2016,TPA,blue,1,30,total_gold,NaN,NaN,blue,1,0.0,0.0,17.0,-106.0,-136.0,400.0,363.0,829.0,1532.0,1862.0,1473.0,1514.0,2290.0,2793.0,2975.0,3497.0,5391.0,5188.0,6938.0,8541.0,9835.0,10428.0,11160.0,11492.0,12184.0,14247.0,14372.0,14594.0,16182.0,16344.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [144]:
final_gold.drop(['index', 'red_or_blue_side_y', 'result_y'], inplace=True, axis=1)

ValueError: labels ['index' 'red_or_blue_side_y' 'result_y'] not contained in axis

In [145]:
final_gold.tail()

,match_id,league,season,year,team_name,red_or_blue_side_x,result_x,game_length,type,player_name,champion,min_0,min_1,min_2,min_3,min_4,min_5,min_6,min_7,min_8,min_9,min_10,min_11,min_12,min_13,min_14,min_15,min_16,min_17,min_18,min_19,min_20,min_21,min_22,min_23,min_24,min_25,min_26,min_27,min_28,min_29,min_30,min_31,min_32,min_33,min_34,min_35,min_36,min_37,min_38,min_39,min_40,min_41,min_42,min_43,min_44,min_45,min_46,min_47,min_48,min_49,min_50,min_51,min_52,min_53,min_54,min_55,min_56,min_57,min_58,min_59,min_60,min_61,min_62,min_63,min_64,min_65,min_66,min_67,min_68,min_69,min_70,min_71,min_72,min_73,min_74,min_75,min_76,min_77,min_78,min_79,min_80
45619,ffee707e7f60869a,LMS,Spring_Season,2016,HKE,red,0,43,support_gold,Alistar,Olleh,0.0,-10.0,-10.0,-16.0,4.0,7.0,-126.0,-51.0,-50.0,375.0,374.0,386.0,389.0,348.0,446.0,303.0,370.0,348.0,393.0,294.0,328.0,356.0,409.0,418.0,422.0,477.0,431.0,135.0,137.0,-102.0,-12.0,42.0,165.0,171.0,130.0,178.0,117.0,274.0,180.0,-58.0,-90.0,-224.0,-697.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45620,ffeff6e4c32e9fd0,LCK,Spring_Season,2015,JAG,blue,0,41,support_gold,Chei,Annie,0.0,0.0,6.0,44.0,51.0,-9.0,23.0,-30.0,182.0,229.0,-224.0,-84.0,-232.0,-192.0,-217.0,-224.0,154.0,291.0,822.0,794.0,802.0,831.0,537.0,446.0,414.0,404.0,386.0,-30.0,-23.0,-461.0,-595.0,-615.0,-644.0,-718.0,-706.0,-1113.0,-1033.0,-575.0,-437.0,-485.0,-936.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45621,ffeff6e4c32e9fd0,LCK,Spring_Season,2015,SKT,red,1,41,support_gold,Thresh,Wolf,0.0,0.0,-6.0,-44.0,-51.0,9.0,-23.0,30.0,-182.0,-229.0,224.0,84.0,232.0,192.0,217.0,224.0,-154.0,-291.0,-822.0,-794.0,-802.0,-831.0,-537.0,-446.0,-414.0,-404.0,-386.0,30.0,23.0,461.0,595.0,615.0,644.0,718.0,706.0,1113.0,1033.0,575.0,437.0,485.0,936.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45622,fff9913c8be5e3fd,LCK,Spring_Season,2017,JAG,red,0,45,support_gold,MissFortune,SnowFlower,-15.0,9.0,-1.0,13.0,2.0,-47.0,-13.0,27.0,72.0,59.0,-343.0,-246.0,-364.0,-212.0,-114.0,-104.0,233.0,318.0,279.0,428.0,430.0,490.0,300.0,266.0,263.0,302.0,443.0,48.0,101.0,-299.0,-401.0,-316.0,-256.0,-226.0,-172.0,-451.0,-294.0,-337.0,-92.0,-137.0,-496.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45623,fff9913c8be5e3fd,LCK,Spring_Season,2017,kt,blue,1,45,support_gold,Mata,Zyra,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [147]:
gold_df.tail()

,match_id,league,season,year,team_name,red_or_blue_side,result,game_length,type,player_name,champion,min_0,min_1,min_2,min_3,min_4,min_5,min_6,min_7,min_8,min_9,min_10,min_11,min_12,min_13,min_14,min_15,min_16,min_17,min_18,min_19,min_20,min_21,min_22,min_23,min_24,min_25,min_26,min_27,min_28,min_29,min_30,min_31,min_32,min_33,min_34,min_35,min_36,min_37,min_38,min_39,min_40,min_41,min_42,min_43,min_44,min_45,min_46,min_47,min_48,min_49,min_50,min_51,min_52,min_53,min_54,min_55,min_56,min_57,min_58,min_59,min_60,min_61,min_62,min_63,min_64,min_65,min_66,min_67,min_68,min_69,min_70,min_71,min_72,min_73,min_74,min_75,min_76,min_77,min_78,min_79,min_80
7599,ffee707e7f60869a,LMS,Spring_Season,2016,HKE,red,0,43,support_gold,Alistar,Olleh,500,500,501,680,1036,1252,1518,1727,1866,2436,2571,2718,2883,3057,3324,3496,3754,3931,4158,4372.0,4633.0,4877.0,5150.0,5354.0,5582.0,5835.0,6090.0,6289.0,6576.0,6758.0,7066.0,7326.0,7839.0,8023.0,8272.0,8545.0,8904.0,9430.0,9620.0,9815.0,9996.0,10519.0,10765.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7600,ffeff6e4c32e9fd0,LCK,Spring_Season,2015,JAG,blue,0,41,support_gold,Chei,Annie,515,515,581,786,961,1123,1301,1442,1792,2045,2197,2488,2624,2795,2941,3086,3742,4002,4784,4919.0,5100.0,5267.0,5492.0,5649.0,5793.0,5959.0,6098.0,6264.0,6424.0,6589.0,6747.0,6903.0,7115.0,7254.0,7389.0,7527.0,7730.0,8522.0,8783.0,8956.0,9230.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7601,ffeff6e4c32e9fd0,LCK,Spring_Season,2015,SKT,red,1,41,support_gold,Thresh,Wolf,515,515,575,742,910,1132,1278,1472,1610,1816,2421,2572,2856,2987,3158,3310,3588,3711,3962,4125.0,4298.0,4436.0,4955.0,5203.0,5379.0,5555.0,5712.0,6294.0,6447.0,7050.0,7342.0,7518.0,7759.0,7972.0,8095.0,8640.0,8763.0,9097.0,9220.0,9441.0,10166.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7602,fff9913c8be5e3fd,LCK,Spring_Season,2017,JAG,red,0,45,support_gold,MissFortune,SnowFlower,500,524,574,755,912,1085,1265,1499,1682,1875,2078,2326,2492,2775,3044,3206,3821,4029,4241,4553.0,4728.0,4926.0,5255.0,5469.0,5642.0,5857.0,6155.0,6342.0,6548.0,6751.0,6941.0,7202.0,7503.0,7746.0,7923.0,8189.0,8469.0,8760.0,9128.0,9304.0,9670.0,9925.0,10215.0,10470.0,10958.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7603,fff9913c8be5e3fd,LCK,Spring_Season,2017,kt,blue,1,45,support_gold,Mata,Zyra,500,500,550,723,880,1061,1221,1404,1579,1937,2085,2286,2423,2909,3253,3426,3608,3803,4242,4524.0,4751.0,4920.0,5181.0,5382.0,5551.0,5723.0,6287.0,6459.0,6676.0,6880.0,7101.0,7299.0,7578.0,8279.0,8870.0,9093.0,9460.0,9904.0,10138.0,10347.0,10810.0,11091.0,11618.0,11826.0,12628.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN